name: Update Submodules

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Update submodules
        run: |
          # Attempt to update submodules, continue even if some fail
          git submodule update --remote --merge || echo "Submodule update failed, proceeding..."
          # Ensure submodules are initialized
          git submodule init
          # Try fetching specific branch if needed
          git submodule foreach 'git fetch origin || true'

      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet; then
            echo "No changes in submodules"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected in submodules"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git commit -am "Update submodules to latest"
          git push origin main
